package nl.hu.inno.incidentendashboard.domain

enum class SafetyRegion {
    GRONINGEN,
    FRIESLAND,
    DRENTHE,
    IJSSSELLAND,
    TWENTE,
    NOORD_EN_OOST_GELDERLAND,
    GELDERLAND_MIDDEN,
    GELDERLAND_ZUID,
    UTRECHT,
    NOORD_HOLLAND_NOORD,
    ZAANSTREEK_WATERLAND,
    KENNEMERLAND,
    AMSTERDAM_AMSTELLAND,
    GOOI_EN_VECHTSTREEK,
    HAAGLANDEN,
    HOLLANDS_MIDDEN,
    ROTTERDAM_RIJNMOND,
    ZUID_HOLLAND_ZUID,
    ZEELAND,
    MIDDEN_EN_WEST_BRABANT,
    BRABANT_NOORD,
    BRABANT_ZUIDOOST,
    LIMBURG_NOORD,
    ZUID_LIMBURG,
    FLEVOLAND
}